version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    container_name: stats_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass



